name: Generate Destined Rivals Placeholder PDF

on:
  schedule:
    # Runs once per day at 11:00 UTC (~7 AM ET during EDT). Edit cron if you want another time.
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate PDF
        env:
          TCGCSV_URL: ${{ secrets.TCGCSV_URL }}
          SET_NAME: 'Destined Rivals'
          OUTPUT_PATH: 'outputs/destined_rivals_placeholders.pdf'
        run: |
          python generate_pdf.py

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: destined-rivals-pdf
          path: outputs/*.pdf