name: Generate Binder Sheet

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"  # Runs daily at 9 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests pandas reportlab

      - name: Install tcgcsv
        run: |
          pip install tcgcsv

      - name: Run tcgcsv
        run: |
          tcgcsv --set "Destined Rivals" --output data.csv

      - name: Download card images
        run: |
          python scripts/download_images.py

      - name: Create binder sheet
        run: |
          python scripts/make_binder_sheet.py

      - name: Commit binder sheet
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add binder_sheets/*.pdf
          git commit -m "Auto-update binder sheet"
          git push
